ENCODER_MAP_ENABLE = yes
HAPTIC_ENABLE = yes
DYNAMIC_MACRO_ENABLE = no
SWAP_HANDS_ENABLE = no

AUDIO_ENABLE = no
MUSIC_ENABLE = no

RGB_MATRIX_ENABLE = yes

VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes
VIALRGB_ENABLE = yes
VIAL_INSECURE = yes