# Build Options
#   change yes to no to disable
#
SWAP_HANDS_ENABLE = yes

OLED_DRIVER = SSD1306

HAPTIC_DRIVER = DRV2605L

RGB_MATRIX_SUPPORTED = yes

#SPACE SAVING
AUDIO_ENABLE = no
MUSIC_ENABLE = no
LTO_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no
